# from https://github.com/abo-abo/swiper/blob/master/.travis.yml
dist: bionic
language: generic
addons:
  apt:
    update: true

jobs:
  include:
    - stage: load
      name: "Load"
      env: EVM_EMACS=emacs-24.5-travis
      script: &load
      - git clone https://github.com/rejeep/evm.git $HOME/.evm
      - export PATH=$HOME/.evm/bin:$PATH
      - evm config path /tmp
      - evm install $EVM_EMACS --use --skip
      - evm use $EVM_EMACS
      - emacs --version
      - emacs --load lsp-haskell.el --funcall lsp-haskell-run-tests
    - stage: load
      name: "Load"
      env: EVM_EMACS=emacs-25.3-travis
      script: &load
    - stage: load
      name: "Load"
      env: EVM_EMACS=emacs-26.3-travis
      script: &load
    - stage: load
      name: "Load"
      env: EVM_EMACS=emacs-git-snapshot-travis
      script: &load
